FROM node:20.10.0-alpine
WORKDIR /transaction_migration

COPY . .
COPY .env.example .env

RUN npm cache clean --force
RUN npm install -g @nestjs/cli

RUN yarn install
RUN yarn build

CMD ["npm", "run", "migration:run"]
