name: Transaction
on: workflow_dispatch
jobs: 
  stage_dev:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3.5.3
      - name: install deps
        run: yarn
      - name: lint
        run: yarn run lint
      - name: unit-test
        run: yarn run test
