name: Transaction

on: workflow_dispatch

jobs:
  stage_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.1'

      - name: get code
        uses: actions/checkout@v3.5.3

      - name: install deps
        run: yarn install

      - name: lint
        run: yarn run lint

      - name: unit-test
        run: yarn run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t book_all-transaction:latest .
          docker tag book_all-transaction:latest ${{ secrets.DOCKER_USERNAME }}/book_all-transaction:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/book_all-transaction:latest
